<?php

include_once 'inc/php/functions.php';

?>

<!doctype html>
<html>

	<head>
	
		<title>WPBuild</title>

		<script type="text/javascript"> less = { env: 'development' };
 </script>
		<link rel="shortcut icon" href="favicon.png" />

		<meta name="description" content="WPBuild is a custom theme builder that strips out all the unnecessary clutter and provides users with useful functions to get them up and running in no time.">
		<meta name="keywords" content="wordpress, wordpress themes, skeleton, blank themes, wordpress builder" />
		<meta name="author" content="Matt Vickers">

		<link href='http://fonts.googleapis.com/css?family=Varela' rel='stylesheet' type='text/css'>

		<link rel="stylesheet/less" type="text/css" href="inc/css/main.less">
		<script src="http://lesscss.googlecode.com/files/less-1.2.1.min.js" type="text/javascript"></script>

	</head>

	<body>

		<div id="beta" class="container">
			
			<div class="content">
				
				<p><strong>Heads up</strong>: This site is a work in progress, but we're trying to make it as great as possible. <a href="http://twitter.com/envex">Contact us</a> if you have a problem!</p>

			</div> <!-- content -->

		</div> <!-- beta -->

		<div id="header" class="container">
			
			<div class="content">
				
				<h1 id="logo"><a href="">WPBuild</a></h1>

				<h2>Hand built themes -- Tailored just for you</h2>

			</div> <!-- content -->

		</div> <!-- header -->

		<div id="content" class="container">
			
			<div class="content">
	
				<form method="POST" action="build.php" class="form-horizontal">
					
					<fieldset id="theme_info">
					
						<div class="group_info">

							<h2>Theme Info</h2>

							<p>We need to know a few details about your theme before you can go any further.</p>
							
						</div> <!-- group_info -->

						<div class="fields">

							<div class="text theme_name"><label for="">Theme Name:</label>
							<input type="text" name="theme_name" title="Mark V" /></div>

							<div class="text author_name"><label for="">Your Name:</label>
							<input type="text" name="author_name" title="Tony Stark"/></div>
	
							<div class="text author_website"><label for="">Your Website:</label>
							<input type="text" name="author_website" title="http://starkindustries.com" /></div>
							
						</div> <!-- fields -->

					</fieldset>

					<fieldset id="css">

						<div class="group_info">

							<h2>CSS</h2>

							<p>By default WordPress uses boring old vanilla CSS.</p>
							<p>We &hearts;
 <a href="http://lesscss.org/">LESS</a>, so we're giving you the option to include it in the theme.....you should!</p>
							
						</div> <!-- group_info -->

						<div class="fields">

							<img src="img/less_logo.png" alt="LessCSS" id="less_logo" />
							
							<?php echo toggle('use_less', array('yes' => 'Use LESS', 'no' => 'Use boring CSS')); ?>

						</div> <!-- fields -->

					</fieldset>

					<fieldset id="functions">

						<div class="group_info">

							<h2>WordPress Functions</h2>

							<p>All the code generated by these options are just base values.</p>
							<p>The code can be re-used to add another menu, widget, etc</p>	

							<h3>Use the Codex</h3>

							<p>When you're building themes the <a href="http://codex.wordpress.org/">WordPress Codex</a> will become your best friend. You'll want to get to know him, spend every waking moment with him and eventually love him like a brother</p>
												
						</div> <!-- group_info -->

						<div class="fields">

							<?php
							if(1 == 1): ?>

							<ul class="list">
								<li id="menu">
									<span class="title">Custom Menu</span>
									<?php echo toggle('has_menu'); ?>
									<p class="desc">Allow users to add/remove pages to your theme with ease.</p>
								</li>
								<li id="widget">
									<span class="title">Widget Area</span>
									<?php echo toggle('has_widget'); ?>
									<p class="desc">A blank canvas</p>
								</li>
								<li id="custom_post_type">
									<span class="title">Custom Post Type</span>
									<?php echo toggle('has_custom_post_type'); ?>
									<p class="desc">When posts and pages just won't cut it.</p>
								</li>
							</ul>


							<?php
							else: ?>
							
 							<ul class="grid">
								<li class="first" id="menu">
									<p>Custom Menu</p>
									<label class="icon">
										<input type="checkbox" name="has_menu">
										<p>Adds a WordPress menu called <em>Main</em> to the header.php template file</p>
									</label>
								</li>
								<li class="second" id="widget">
						            <p>Widget Area</p>
									<label class="icon">
										<input type="checkbox" name="has_widget">
										<p>Adds a WordPress widget area called <em>Sidebar</em> to the sidebar.php template file</p>
									</label>									
								</li>
								<li class="third" id="custom_post_type">
						            <p>Custom Post Type</p>
									<label class="icon">
										<input type="checkbox" name="has_custom_post_type">
										<p>Creates a Custom Post Type. <strong>Singular name please</strong></p>
										<p><small>Generates a file in inc/php/custom_post_type.php</small></p>
									</label>
									<label class="control-label" for="">Post Type Name</label>
									<input type="text" name="custom_post_type_name" />									
								</li>
							</ul> 

							<?php
							endif; ?>
							
						</div> <!-- fields -->

					</fieldset>

					<fieldset id="download">

						<input type="submit" value="Download your handcrafted theme!" />


					</fieldset>

				</form>	
				
			</div> <!-- content -->

		</div> <!-- content -->

		<div id="footer" class="container">
			
			<div class="content">

				<div class="left">

					<h2>Did we miss something? <a href="https://twitter.com/intent/tweet?screen_name=envex&amp;
text=I%20think%20WPBuild%20needs...%20%23WPBuild" class="button">Suggest a function/feature!</a></h2>

				</div> <!-- left -->

				<div class="right">

					<h3>What is WPBuild?</h3>

					<p>WPBuild is a custom theme builder that strips out all the unnecessary clutter and provides you with useful functions to get you up and running in no time.</p>

					<h4>Some &hearts; from WPBuild</h4>

					<p>The icons are <a href="http://pictos.cc/">Pictos by Drew Wilson</a> and the Toggles are inspired by <a href="http://rogieking.com/">Rogie King</a></p>

				</div> <!-- right -->
				
				<p class="copyright">
					<span>
						<a href="https://twitter.com/share" class="twitter-share-button" data-via="envex" data-hashtags="wpbuild">Tweet</a>
					</span>
					Copyright <?php echo date('Y'); ?> WPBuild &bull;
					 <a href="">Envex Labs</a> &bull;
					 <a href="">Facet</a>
				</p>

			</div> <!-- content -->

		</div> <!-- footer -->

		<script>
			!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];
if(!d.getElementById(id)){js=d.createElement(s);
js.id=id;
js.src="//platform.twitter.com/widgets.js";
fjs.parentNode.insertBefore(js,fjs);
}}(document,"script","twitter-wjs");

		</script>
		
		<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.js"></script>

		<script type="text/javascript" src="inc/js/functions.js"></script>
		<script type="text/javascript" src="inc/js/main.js"></script>

		<script type="text/javascript">

			var _gaq = _gaq || [];

			_gaq.push(['_setAccount', 'UA-10321164-7']);

			_gaq.push(['_trackPageview']);


			(function() {
			var ga = document.createElement('script');
 ga.type = 'text/javascript';
 ga.async = true;

			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

			var s = document.getElementsByTagName('script')[0];
 s.parentNode.insertBefore(ga, s);

			})();


		</script>

	</body>

</html>